# Generated by Django 2.0.4 on 2019-02-23 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190223_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='created_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
