# Generated by Django 2.1.5 on 2019-02-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190223_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product')},
        ),
    ]
