version: "3.6"
services:
  nginx:
    image: winiciuscota/mercsales-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - api_net
    depends_on:
      - webapp
      - webapi

  webapp:
    image: winiciuscota/mercsales-app
    restart: always
    networks:
      - api_net
    depends_on:
      - webapi

  webapi:
    image: winiciuscota/mercsales-api
    command: python src/manage.py runserver 0.0.0.0:8000
    restart: always
    networks:
      - api_net
      - postgres_net
    depends_on:
      - postgres
    environment:
      DJANGO_ALLOWED_HOSTS: webapi
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres_net
    volumes:
      - postgresdb:/var/lib/postgresql/data

networks:
  api_net:
  postgres_net:

volumes:
  postgresdb:
